export const mobiledata = [
    {
        id: "1",
        brand: "samsung",
        mobile_name: "Samsung A52 (black)",
        mobile_img_1: "/images/samsung/a52_1.jpeg",
        mobile_img_2: "/images/samsung/a52_2.jpeg",
        mobile_img_3: "/images/samsung/a52_3.jpeg",
        mobile_img_4: "/images/samsung/a52_4.jpeg",
        mobile_img_5: "/images/samsung/a52_4.jpeg",
        ram: "8GB",
        rom: "128 GB",
        display: "16.51 cm (6.5 inch) Full HD+ Display",
        battery: "4500 mAh Lithium-ion Battery",
        processer: "Qualcomm Snapdragon 720G Processor",
        camara: "64MP + 12MP + 5MP + 5MP | 32MP Front Camera",
        price: 27999,
        alt: "samsung a52",
        quantity: 1
    },
    {
        id: "2",
        brand: "mi",
        mobile_name: "Mi 10i (Midnight Black)",
        mobile_img_1: "/images/mi/10i_1.jpeg",
        mobile_img_2: "/images/mi/10i_2.jpeg",
        mobile_img_3: "/images/mi/10i_3.jpeg",
        mobile_img_4: "/images/mi/10i_4.jpeg",
        mobile_img_5: "/images/mi/10i_5.jpeg",
        ram: "8 GB RAM",
        rom: "128 Gb Rom",
        display: "16.94 cm (6.67 inch) Full HD+ Display",
        battery: "4820 mAh Battery",
        processer: "Qualcomm® Snapdragon™ 750G Processor",
        camara: "108MP + 8MP + 2MP + 2MP | 16MP Front Camera",
        price: 22499,
        alt: "samsung a52",
        quantity: 1
    },
    {
        id: "3",
        brand: "poco",
        mobile_name: "POCO M2  PRO (Black)",
        mobile_img_1: "/images/poco/m2pro_1.jpeg",
        mobile_img_2: "/images/poco/m2pro_2.jpeg",
        mobile_img_3: "/images/poco/m2pro_3.jpeg",
        mobile_img_4: "/images/poco/m2pro_4.jpeg",
        mobile_img_5: "/images/poco/m2pro_5.jpeg",
        ram: "6 Gb RAM",
        rom: "128 Gb Rom",
        display: "16.59 cm (6.53 inch) Full HD+ Display",
        battery: "6000 mAh Lithium-ion Polymer Battery",
        processer: "Qualcomm Snapdragon 662 Processor",
        camara: "108MP + 8MP + 2MP + 2MP | 16MP Front Camera",
        price: 22499,
        alt: "samsung a52",
        quantity: 1
    },
    {
        id: "4",
        brand: "realme",
        mobile_name: "realme 8 Pro (Black)",
        mobile_img_1: "/images/realme/8pro_1.jpeg",
        mobile_img_2: "/images/realme/8pro_2.jpeg",
        mobile_img_3: "/images/realme/8pro_3.jpeg",
        mobile_img_4: "/images/realme/8pro_4.jpeg",
        mobile_img_5: "/images/realme/8pro_5.jpeg",
        ram: "8 Gb RAM",
        rom: "128 Gb Rom",
        display: "16.26 cm (6.4 inch) Full HD+ Display",
        battery: "4500 mAh Battery",
        processer: "Qualcomm Snapdragon 720G Processor",
        camara: "108MP + 8MP + 2MP + 2MP | 16MP Front Camera",
        price: 19999,
        alt: "samsung a52",
        quantity: 1
    },
    {
        id: "5",
        brand: "Vivo",
        mobile_name: "Vivo V20 (Black)",
        mobile_img_1: "/images/vivo/v20_1.jpeg",
        mobile_img_2: "/images/vivo/v20_2.jpeg",
        mobile_img_3: "/images/vivo/v20_3.jpeg",
        mobile_img_4: "/images/vivo/v20_4.jpeg",
        mobile_img_5: "/images/vivo/v20_5.jpeg",
        ram: "8 GB RAM",
        rom: "128 ROM",
        display: "17.02 cm (6.7 inch) Full HD+ Display",
        battery: "4000 mAh Lithium-ion Battery",
        processer: "Qualcomm Snapdragon 720G Processor",
        camara: "108MP + 8MP + 2MP + 2MP | 16MP Front Camera",
        price: 34499,
        alt: "samsung a52",
        quantity: 1
    },
    {
        id: "6",
        brand: "OPPO",
        mobile_name: "Vivo V20 (Black)",
        mobile_img_1: "/images/oppo/a33_1.jpeg",
        mobile_img_2: "/images/oppo/a33_2.jpeg",
        mobile_img_3: "/images/oppo/a33_3.jpeg",
        mobile_img_4: "/images/oppo/a33_4.jpeg",
        mobile_img_5: "/images/oppo/a33_5.jpeg",
        ram: "8 GB RAM",
        rom: "128 ROM",
        display: "17.02 cm (6.7 inch) Full HD+ Display",
        battery: "4200 mAh Lithium-ion Battery",
        processer: "Qualcomm Snapdragon 720G Processor",
        camara: "108MP + 8MP + 2MP + 2MP | 16MP Front Camera",
        price: 8999,
        alt: "samsung a52",
        quantity: 1
    },
    {
        id: "7",
        brand: "ONE PLUS",
        mobile_name: "OnePlus 9 (Black)",
        mobile_img_1: "/images/oneplus/9_1.jpg",
        mobile_img_2: "/images/oneplus/9_2.jpeg",
        mobile_img_3: "/images/oneplus/9_3.jpeg",
        mobile_img_4: "/images/oneplus/9_4.jpeg",
        mobile_img_5: "/images/oneplus/9_5.jpeg",
        ram: "8 GB RAM",
        rom: "128 ROM",
        display: "6.55 Inches Fluid AMOLED display with 120 Hz of Refresh rate",
        battery: "4500 mAh Lithium-ion Battery",
        processer: "Qualcomm Snapdragon 870 5G  Processor",
        camara: "108MP + 8MP + 2MP + 2MP | 16MP Front Camera",
        price: 49999,
        alt: "samsung a52",
        quantity: 1
    },
    {
        id: "8",
        brand: "samsung",
        mobile_name: "Samsung A72 (Black)",
        mobile_img_1: "/images/samsung/a72_1.jpeg",
        mobile_img_2: "/images/samsung/a72_2.jpeg",
        mobile_img_3: "/images/samsung/a72_3.jpeg",
        mobile_img_4: "/images/samsung/a72_4.jpeg",
        mobile_img_5: "/images/samsung/a72_5.jpeg",
        ram: "8 GB RAM",
        rom: "128 ROM",
        display: "17.02 cm (6.7 inch) Full HD+ Display",
        battery: "5000 mAh Lithium-ion Battery",
        processer: "Qualcomm Snapdragon 720G Processor",
        camara: "108MP + 8MP + 2MP + 2MP | 16MP Front Camera",
        price: 34499,
        alt: "samsung a52",
        quantity: 1
    },
    {
        id: "9",
        brand: "mi",
        mobile_name: "Redmi Note 10 (Black)",
        mobile_img_1: "/images/mi/note10_1.jpeg",
        mobile_img_2: "/images/mi/note10_2.jpeg",
        mobile_img_3: "/images/mi/note10_3.jpeg",
        mobile_img_4: "/images/mi/note10_4.jpeg",
        mobile_img_5: "/images/mi/note10_5.jpeg",
        ram: "8 GB RAM",
        rom: "128 Gb Rom",
        display: "16.94 cm (6.67 inch) Full HD+ Display",
        battery: "4820 mAh Battery",
        processer: "Qualcomm® Snapdragon™ 750G Processor",
        camara: "108MP + 8MP + 2MP + 2MP | 16MP Front Camera",
        price: 22499,
        alt: "samsung a52",
        quantity: 1
    },
    {
        id: "10",
        brand: "poco",
        mobile_name: "POCO X3(Black)",
        mobile_img_1: "/images/poco/x3_1.jpeg",
        mobile_img_2: "/images/poco/x3_2.jpeg",
        mobile_img_3: "/images/poco/x3_3.jpeg",
        mobile_img_4: "/images/poco/x3_4.jpeg",
        mobile_img_5: "/images/poco/x3_5.jpeg",
        ram: "6 Gb RAM",
        rom: "128 Gb Rom",
        display: "16.59 cm (6.53 inch) Full HD+ Display",
        battery: "6000 mAh Lithium-ion Polymer Battery",
        processer: "Qualcomm Snapdragon 662 Processor",
        camara: "108MP + 8MP + 2MP + 2MP | 16MP Front Camera",
        price: 22499,
        alt: "samsung a52",
        quantity: 1
    },
    {
        id: "11",
        brand: "realme",
        mobile_name: "realme X7(Black)",
        mobile_img_1: "/images/realme/x7_1.jpeg",
        mobile_img_2: "/images/realme/x7_2.jpeg",
        mobile_img_3: "/images/realme/x7_3.jpeg",
        mobile_img_4: "/images/realme/x7_4.jpeg",
        mobile_img_5: "/images/realme/x7_5.jpeg",
        ram: "8 Gb RAM",
        rom: "128 Gb Rom",
        display: "16.26 cm (6.4 inch) Full HD+ Display",
        battery: "4500 mAh Battery",
        processer: "Qualcomm Snapdragon 720G Processor",
        camara: "108MP + 8MP + 2MP + 2MP | 16MP Front Camera",
        price: 19999,
        alt: "samsung a52",
        quantity: 1
    },
    {
        id: "12",
        brand: "Vivo",
        mobile_name: "Vivo Y21s (Black)",
        mobile_img_1: "/images/vivo/y21s_1.jpeg",
        mobile_img_2: "/images/vivo/y21s_2.jpeg",
        mobile_img_3: "/images/vivo/y21s_3.jpeg",
        mobile_img_4: "/images/vivo/y21s_4.jpeg",
        mobile_img_5: "/images/vivo/y21s_5.jpeg",
        ram: "8 GB RAM",
        rom: "128 ROM",
        display: "17.02 cm (6.7 inch) Full HD+ Display",
        battery: "4000 mAh Lithium-ion Battery",
        processer: "Qualcomm Snapdragon 720G Processor",
        camara: "108MP + 8MP + 2MP + 2MP | 16MP Front Camera",
        price: 34499,
        alt: "samsung a52",
        quantity: 1
    },
    {
        id: "13",
        brand: "OPPO",
        mobile_name: "OPPO F17 PRO (Black)",
        mobile_img_1: "/images/oppo/_1.jpeg",
        mobile_img_2: "/images/oppo/_2.jpeg",
        mobile_img_3: "/images/oppo/_3.jpeg",
        mobile_img_4: "/images/oppo/_4.jpeg",
        mobile_img_5: "/images/oppo/_5.jpeg",
        ram: "8 GB RAM",
        rom: "128 ROM",
        display: "17.02 cm (6.7 inch) Full HD+ Display",
        battery: "4200 mAh Lithium-ion Battery",
        processer: "Qualcomm Snapdragon 720G Processor",
        camara: "108MP + 8MP + 2MP + 2MP | 16MP Front Camera",
        price: 8999,
        alt: "samsung a52",
        quantity: 1
    },
    {
        id: "14",
        brand: "ONE PLUS",
        mobile_name: "OnePlus (Black)",
        mobile_img_1: "/images/oneplus/9r_1.jpeg",
        mobile_img_2: "/images/oneplus/9r_2.jpeg",
        mobile_img_3: "/images/oneplus/9r_3.jpeg",
        mobile_img_4: "/images/oneplus/9r_4.jpeg",
        mobile_img_5: "/images/oneplus/9r_5.jpeg",
        ram: "8 GB RAM",
        rom: "128 ROM",
        display: "6.55 Inches Fluid AMOLED display with 120 Hz of Refresh rate",
        battery: "4500 mAh Lithium-ion Battery",
        processer: "Qualcomm Snapdragon 870 5G  Processor",
        camara: "108MP + 8MP + 2MP + 2MP | 16MP Front Camera",
        price: 49999,
        alt: "samsung a52",
        quantity: 1
    },

]



